title: "Dashboard"
subtitle: "YAND"

default:
  surface: "#131313"
  foreground: "#ffffff"
  background: "#444444"

weather:
  enabled: true
  timezone: "Europe/Berlin"
  latitude: "48.2085"
  longtitude: "16.3721"

services:
  - name: "Example Category"
    items:
      - name: "Example"
        logo: "example.webp"
        subtitle: "Example Description"
        tag: "tag"
        url: "https://example.com/"
