version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: "increase"
    directory: "/app"
    schedule:
      interval: "weekly"
      day: "monday"
    groups:
      all:
        patterns:
          - "*"
