version: '3.8'
services:
  yand:
    image: ghcr.io/0xk1f0/YAND:latest
    ports:
      - 80:80
    volumes:
      - ./data/assets:/assets
      - ./data/config:/config
    environment:
      TZ: Europe/Vienna
      # CONFIG_DIR: '/some/other/path'
      # DEFAULT_DIR: '/some/other/path'
      # ICON_PATH: '/some/other/path'
    restart: unless-stopped
