version: "3"
name: yand
services:
  yand:
    image: ghcr.io/0xk1f0/yand:latest
    ports:
      - 80:8080
    volumes:
      - ./data/assets:/assets
      - ./data/config:/config
    environment:
      TZ: Europe/Vienna
    restart: unless-stopped
