version: '3.8'
services:
  yand:
    image: ghcr.io/0xk1f0/yand:latest
    ports:
      - 80:80
    volumes:
      - ./data/assets:/assets
      - ./data/config:/config
    environment:
      TZ: Europe/Vienna
      # CONFIG: '/some/custom/config.toml'
      # DEFAULT: '/some/default/config.toml'
      # ICON_PATH: '/some/asset/path'
    restart: unless-stopped
