apiVersion: v1
kind: Pod
metadata:
  name: yand
spec:
  containers:
    - image: ghcr.io/0xk1f0/yand:latest
      name: yand
      env:
        - name: TZ
          value: Europe/Vienna
      ports:
        - containerPort: 8080
          hostPort: 80
      volumeMounts:
        - mountPath: /assets
          name: data-assets
        - mountPath: /config
          name: data-config
  volumes:
    - hostPath:
        path: ./data/assets
        type: DirectoryOrCreate
      name: data-assets
    - hostPath:
        path: ./data/config
        type: DirectoryOrCreate
      name: data-config
