FROM node:22-slim as builder

# change workdir
WORKDIR /build

COPY package.json \
package-lock.json \
astro.config.mjs \
tailwind.config.mjs \
tsconfig.json ./

# Install dependencies
RUN npm install

# app files
COPY src ./src

# and build webapp
RUN npm run build

# remove unnecessary dependencies
RUN npm prune --omit=dev

FROM node:22-slim

# change workdir
WORKDIR /app

# copy app files
COPY --from=builder /build/dist ./dist
COPY --from=builder /build/node_modules ./node_modules

# necessary paths
RUN mkdir -p /config
RUN ln -s /app/dist/client/icons /assets

# copy misc files
COPY misc/entrypoint.sh /
COPY misc/config.yaml /config

# expose 80
EXPOSE 80

# start app
CMD ["/entrypoint.sh"]
