name: Build and Publish

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'misc/**'
      - 'astro.conf.mjs'
      - 'tsconfig.json'
      - 'package.json'
      - 'Containerfile'
  pull_request:
    branches: [ "master" ]
    paths:
      - '.github/workflows/**'
      - 'src/**'
      - 'misc/**'
      - 'astro.conf.mjs'
      - 'tsconfig.json'
      - 'package.json'
      - 'Containerfile'

jobs:
  build-npm:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'
      - name: Build YAND
        run: |
          npm install
          npm run build
      - name: Publish YAND package
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-container:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Build Image
        id: buildah
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ github.repository }}
          tags: latest
          context: ./
          containerfiles: |
            ./Containerfile
      - name: Push to GHCR
        if: ${{ github.event_name != 'pull_request' }}
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.buildah.outputs.image }}
          tags: ${{ steps.buildah.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Cleanup registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/delete-package-versions@v5
        with:
          package-name: yand
          package-type: container
          min-versions-to-keep: 3
