name: Build and Publish Latest Image

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/**'
      - 'app/src/**'
      - 'app/astro.conf.mjs'
      - 'app/tsconfig.json'
      - 'app/package.json'
      - 'app/Containerfile'
  pull_request:
    branches: [ "master" ]
    paths:
      - '.github/workflows/**'
      - 'app/src/**'
      - 'app/astro.conf.mjs'
      - 'app/tsconfig.json'
      - 'app/package.json'
      - 'app/Containerfile'

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Build Image
        id: buildah
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ github.repository }}
          tags: latest
          context: ./app
          containerfiles: |
            ./app/Containerfile
      - name: Push to GHCR
        if: ${{ github.event_name != 'pull_request' }}
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.buildah.outputs.image }}
          tags: ${{ steps.buildah.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Cleanup registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/delete-package-versions@v5
        with:
          package-name: yand
          package-type: container
          min-versions-to-keep: 3
